### ISSUE TITLE
Add support for non-vexriscv CPUs to Linux-on-LiteX-Vexriscv and rename to Linux-on-LiteX?

### ISSUE THREAD

**Issue by mithro** [litex-hub/ideas#1]
It would be really cool to transform this repository from `linux-on-litex-vexriscv` to `linux-on-litex` by supporting non-vexriscv CPUs.

It should be pretty trivial to support the mor1kx (as Linux on LiteX was originally develop for that CPU).

The possible future CPUs that might make some sense to support are;
 - [ ] `rocket` - This was added by @gsomlo to LiteX recently and rocket has been a target for RISC-V Linux for a long time. This should hopefully be easy and would test things for 64bit?
 - [ ] `power` - `microwatt` or other power processor would need to be added to LiteX first.
 - [ ] `sh2` / `sh4` - `j-core` or other SH processor would need to be added to LiteX first.

It would allow better comparison on things like;
 * If the ISA has an effect (`riscv` vs `power` vs `or1k`)
 * How 64bit verse 32bit (`vexriscv` vs `rocket`)
 * The implementation (`vexriscv` vs `rocket`)
 * etc...

**Comment by enjoy-digital** [comment]
@mithro: i just created https://github.com/litex-hub/ideas to track general ideas/long term plans and move this to it.

**Comment by gsomlo** [comment]
>     * [ ]  `rocket` - This was added by @gsomlo to LiteX recently and rocket has been a target for RISC-V Linux for a long time. This should hopefully be easy and would test things for 64bit?
I currently have a write-up about that [here](http://www.contrib.andrew.cmu.edu/~somlo/BTCP/) (including build instructions for nexys4ddr and ecp5versa). Mostly straightforward BBL + stock Linux, with only a minimal set of hacks:
- added BBL driver for the LiteX UART (will push upstream once I'm confident that LiteX's CSR alignment situation on 64bit is stable, and/or when I figure out how to specify it all via DTS)
- added hard-coded DTS to BBL -- that should be provided by the LiteX bios/firmware, but for now I took the path of least resistance :)
- I'm currently advertising `imafdc` support via DTS, which is a _blatant lie_ -- it's `imac` only, but BBL should add `fd` itself when exposing the dtb to linux if softfloat handler support is compiled in. It doesn't do so at the moment, but should -- it's a patch I need to write and submit upstream.
As for Linux, I've only added the LiteX ethernet driver I cribbed from `linux-on-vexriscv` and slightly adapted to work with 64bit CSRs, and a `litex_defconfig` file to make it easy to build.

I'd be happy to upload those instructions wherever you all think they might be most useful/visible, but I'm also hoping to minimize/eliminate a large part of them by just upstreaming the current hacks I have going on :)

**Comment by enjoy-digital** [comment]
Linux-on-LiteX-Vexriscv is not going to support others CPU than VexRiscv. There are now various way to run Linux with LiteX: https://github.com/enjoy-digital/litex/wiki/Run-Linux-On-Your-SoC and we are trying to share as maximum as possible between projects (LiteX targets/components, drivers, dts generation). Anyone with interest and time is free to give a try to a project that would support Linux with all CPUs at once.
