### ISSUE TITLE
Define how to track Linux kernel patches

### ISSUE THREAD

**Issue by enjoy-digital** [litex-hub/ideas#3]
We currently have two different approaches:
- https://github.com/litex-hub/linux is a fork with our kernel patches integrated.
- https://github.com/litex-hub/linux-on-litex-vexriscv stores the kernel patches that are applied by buildroot.
See what approach is the best for development/maintenance.

**Comment by mithro** [comment]
@enjoy-digital 

My thinking is that;
 1. We want https://github.com/litex-hub/linux to be a linux kernel with our patches. 
 1. The kernel patches in https://github.com/litex-hub/linux-on-litex-vexriscv used for buildroot should be generated from 1.

[For the SymbiFlow project, I wrote up the following guide](https://docs.google.com/document/d/1JVWkXxeSanAna8IRt0I49sG4aFS3Unlq693-HsQ0B0U/edit) which could work here.

**Comment by frantony** [comment]
@enjoy-digital @mithro 

We can use ``BR2_LINUX_KERNEL_CUSTOM_GIT``, ``BR2_LINUX_KERNEL_CUSTOM_REPO_URL`` and
``BR2_LINUX_KERNEL_CUSTOM_REPO_VERSION`` buildroot options.

See https://github.com/buildroot/buildroot/blob/master/linux/Config.in for details.

**Comment by enjoy-digital** [comment]
We are now relying on a branch of https://github.com/litex-hub/linux to generate the kernel image and no longer using local patches with Buildroot. In the short/mid term, all projects running Linux with LiteX should be able to use the same branch.
